import { StyleSheet } from 'react-native';

export type ThemeMode = 'day' | 'night';

const colors = {
  white: '#FFFFFF',
  gold100: '#F3F4F6',
  gold300: '#000000',
  navy500: '#FFFFFF',
  midnight900: '#FAFAFA',
};

const nightStyleObject = {
  // Removed duplicate landingWrap and landingContent
  // Removed duplicate landingTopMenu
  // Removed duplicate landingTopMenuText
  root: {
    flex: 1,
    backgroundColor: '#FFFFFF',
    backgroundImage: 'none',
  },
  dashboardShell: {
    flex: 1,
    flexDirection: 'row',
    padding: 14,
    gap: 14,
  },
  dashboardShellCompact: {
    flexDirection: 'column',
    padding: 0,
    gap: 0,
  },
  dashboardShellCompactContent: {
    flexGrow: 1,
    padding: 10,
    gap: 10,
  },
  dashboardMainPaneCompact: {
    flex: undefined,
    minHeight: '80vh',
  },
  dashboardSidebar: {
    width: 288,
    borderRadius: 12,
    backgroundColor: 'rgba(0,0,0,0.02)',
    backdropFilter: 'blur(18px) saturate(1.4)',
    WebkitBackdropFilter: 'blur(18px) saturate(1.4)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    boxShadow: '0 8px 32px rgba(0,0,0,0.28), inset 0 0.5px 0 rgba(0,0,0,0.03)',
    paddingHorizontal: 14,
    paddingTop: 12,
    paddingBottom: 10,
    gap: 6,
  },
  dashboardSidebarSmooth: {
    transitionProperty: 'width, padding',
    transitionDuration: '260ms',
    transitionTimingFunction: 'cubic-bezier(0.22, 0, 0.18, 1)',
  },
  dashboardSidebarCompact: {
    width: '100%',
    borderRadius: 0,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.08)',
    paddingTop: 12,
  },
  dashboardSidebarCollapsed: {
    width: 92,
    paddingHorizontal: 10,
    alignItems: 'center',
  },
  dashboardCollapsedNavSection: {
    gap: 4,
    alignItems: 'center',
    width: '100%',
    paddingTop: 4,
  },
  dashboardCollapsedNavItem: {
    width: 48,
    height: 48,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'transparent',
  },
  dashboardCollapsedNavItemActive: {
    backgroundColor: 'rgba(0,0,0,0.04)',
  },
  dashboardTenantHeader: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.02)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginHorizontal: 2,
    marginTop: 4,
  },
  dashboardTenantHeaderActive: {
    borderColor: 'rgba(0,0,0,0.25)',
    backgroundColor: 'rgba(0,0,0,0.03)',
  },
  dashboardTenantHeaderName: {
    color: '#374151',
    fontSize: 13,
    fontWeight: '600',
    flex: 1,
  },
  dashboardTenantAvatar: {
    width: 28,
    height: 28,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(214,204,235,0.18)',
    backgroundColor: 'rgba(0,0,0,0.03)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardTenantAvatarSmall: {
    width: 20,
    height: 20,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: 'rgba(214,204,235,0.18)',
    backgroundColor: 'rgba(0,0,0,0.03)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardTenantPill: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.03)',
    paddingHorizontal: 10,
    paddingVertical: 5,
    marginHorizontal: 2,
    marginTop: 4,
  },
  dashboardTenantPillActive: {
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.04)',
  },
  dashboardTenantPillText: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '600',
    flex: 1,
  },
  dashboardBrandWrap: {
    gap: 0,
    paddingHorizontal: 0,
    paddingTop: 4,
    paddingBottom: 6,
  },
  dashboardBrandTopRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  dashboardHamburgerButton: {
    width: 32,
    height: 32,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundColor: 'rgba(0,0,0,0.02)',
    alignItems: 'center',
    justifyContent: 'center',
    flexShrink: 0,
  },
  dashboardHamburgerButtonText: {
    color: '#111111',
    fontSize: 18,
    fontWeight: '800',
    lineHeight: 20,
  },
  dashboardCollapsedLogo: {
    width: 34,
    height: 34,
    borderRadius: 8,
    resizeMode: 'contain',
  },
  dashboardBrand: {
    color: colors.white,
    fontSize: 22,
    fontWeight: '800',
  },
  dashboardSubBrand: {
    color: '#6B7280',
    fontSize: 11,
  },
  dashboardCreateButton: {
    borderRadius: 12,
    backgroundColor: '#2E86EE',
    minHeight: 42,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dashboardCreateButtonText: {
    color: '#111111',
    fontSize: 14,
    fontWeight: '700',
  },
  dashboardNavSection: {
    gap: 2,
  },
  dashboardNavIcon: {
    fontSize: 17,
    width: 26,
    textAlign: 'center',
    color: 'rgba(214,204,235,0.70)',
  },
  dashboardNavDivider: {
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.02)',
    marginVertical: 4,
  },
  dashboardSectionLabel: {
    color: '#9CA3AF',
    fontSize: 11,
    fontWeight: '700',
    marginTop: 2,
    paddingHorizontal: 6,
  },
  dashboardNavItem: {
    borderRadius: 8,
    paddingHorizontal: 10,
    minHeight: 36,
    paddingVertical: 5,
    backgroundColor: 'transparent',
    justifyContent: 'center',
  },
  dashboardNavItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dashboardNavItemIcon: {
    width: 24,
    height: 24,
    resizeMode: 'contain',
  },
  dashboardNavItemActive: {
    backgroundColor: 'rgba(0,0,0,0.04)',
  },
  dashboardTenantNavGroup: {
    gap: 6,
  },
  dashboardTenantChevron: {
    color: '#1F2937',
    fontSize: 13,
    fontWeight: '800',
    marginLeft: 'auto',
  },
  dashboardTenantNavList: {
    gap: 2,
    paddingLeft: 4,
  },
  dashboardTenantNavItem: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.12)',
    paddingHorizontal: 8,
    minHeight: 34,
    paddingVertical: 5,
    justifyContent: 'center',
  },
  dashboardTenantNavItemCreate: {
    borderStyle: 'dashed' as any,
    borderColor: 'rgba(214,204,235,0.18)',
    backgroundColor: 'transparent',
  },
  dashboardTenantNavItemActive: {
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.04)',
  },
  dashboardTenantNavItemRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dashboardTenantNavItemText: {
    color: '#374151',
    fontSize: 11,
    fontWeight: '600',
  },
  dashboardNavItemText: {
    color: '#374151',
    fontSize: 14,
    fontWeight: '600',
  },
  dashboardNavItemDesc: {
    color: 'rgba(0,0,0,0.45)',
    fontSize: 10,
    fontWeight: '600',
    letterSpacing: 0.3,
    textTransform: 'uppercase',
  },
  dashboardNavItemTextActive: {
    color: '#111111',
    fontWeight: '700',
  },
  dashboardRoleItem: {
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
    paddingHorizontal: 8,
    minHeight: 26,
    paddingVertical: 3,
    backgroundColor: 'rgba(0,0,0,0.80)',
    justifyContent: 'center',
  },
  dashboardRoleItemActive: {
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  dashboardRoleItemText: {
    color: '#374151',
    fontSize: 11,
    fontWeight: '600',
  },
  dashboardRoleItemTextActive: {
    color: '#111111',
  },
  dashboardSidebarFooter: {
    marginTop: 'auto',
    gap: 4,
  },
  dashboardSettingsMenu: {
    gap: 3,
    paddingLeft: 8,
  },
  dashboardSidebarAction: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.88)',
    paddingHorizontal: 8,
    minHeight: 30,
    paddingVertical: 4,
    justifyContent: 'center',
  },
  dashboardSidebarActionActive: {
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  dashboardSidebarActionText: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '600',
  },
  dashboardSidebarActionTextActive: {
    color: '#111111',
  },
  dashboardUserText: {
    color: '#6B7280',
    fontSize: 11,
    lineHeight: 16,
    paddingHorizontal: 2,
  },
  dashboardMainPane: {
    flex: 1,
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    backdropFilter: 'blur(20px) saturate(1.5)',
    WebkitBackdropFilter: 'blur(20px) saturate(1.5)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    boxShadow: '0 8px 32px rgba(0,0,0,0.32), inset 0 0.5px 0 rgba(255,255,255,0.06)',
    overflow: 'hidden',
  },
  dashboardMainHeader: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
    backgroundColor: 'transparent',
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dashboardMainHeaderCompact: {
    alignItems: 'flex-start',
    gap: 10,
  },
  dashboardMainTitle: {
    color: '#111111',
    fontSize: 30,
    fontWeight: '800',
  },
  dashboardMainSubtitle: {
    color: '#6B7280',
    fontSize: 13,
    marginTop: 2,
  },
  dashboardMainActions: {
    flexDirection: 'row',
    gap: 6,
  },
  dashboardMainActionsCompact: {
    width: '100%',
    justifyContent: 'flex-start',
    flexWrap: 'wrap',
  },
  dashboardHeaderButton: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.06)',
    paddingHorizontal: 10,
    minHeight: 34,
    paddingVertical: 6,
    justifyContent: 'center',
  },
  dashboardHeaderButtonText: {
    color: '#111111',
    fontSize: 12,
    fontWeight: '700',
  },
  dashboardHeaderPrimaryButton: {
    borderRadius: 10,
    backgroundColor: '#111111',
    paddingHorizontal: 10,
    minHeight: 34,
    paddingVertical: 6,
    justifyContent: 'center',
  },
  dashboardHeaderPrimaryButtonText: {
    color: '#111111',
    fontSize: 12,
    fontWeight: '700',
  },
  dashboardMainBody: {
    flex: 1,
  },
  dashboardBottomActionBar: {
    borderTopWidth: 1,
    borderTopColor: 'rgba(0,0,0,0.06)',
    backgroundColor: '#111111',
    paddingHorizontal: 18,
    paddingVertical: 12,
    position: 'relative' as any,
    zIndex: 1,
  },
  dashboardBottomActionContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
  },
  dashboardBottomStatusWrap: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  dashboardBottomActionContentCompact: {
    flexDirection: 'column',
    alignItems: 'stretch',
  },
  dashboardBottomStatusText: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '600',
  },
  dashboardBottomStatusIcon: {
    width: 16,
    height: 16,
    resizeMode: 'contain',
  },
  dashboardDraftBanner: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,211,50,0.2)',
    paddingHorizontal: 18,
    paddingVertical: 8,
    backgroundColor: 'rgba(0,0,0,0.04)',
  },
  dashboardDraftText: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '600',
  },
  pressableFeedback: {
    opacity: 1,
    transform: [{ scale: 1 }],
  },
  pressableFeedbackPressed: {
    opacity: 0.9,
    transform: [{ scale: 0.985 }],
  },
  topbar: {
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.2)',
    paddingHorizontal: 14,
    paddingTop: 10,
    paddingBottom: 10,
    gap: 12,
  },
  topbarTitleRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 10,
  },
  brandWrap: {
    gap: 4,
  },
  brand: {
    color: colors.white,
    fontSize: 16,
    fontWeight: '800',
  },
  pageTabs: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  pageWrap: {
    flex: 1,
  },
  pageContent: {
    padding: 12,
    gap: 10,
    paddingBottom: 18,
  },
  pageContentTight: {
    padding: 10,
    gap: 8,
    paddingBottom: 14,
  },
  sectionEyebrow: {
    color: 'rgba(0,0,0,0.55)',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
  },
  sectionLeadText: {
    color: 'rgba(0,0,0,0.7)',
    fontSize: 13,
    lineHeight: 19,
    fontWeight: '600',
  },
  tenantWidgetGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    alignItems: 'flex-start',
  },
  tenantWidgetBlur: {
    borderRadius: 14,
    overflow: 'hidden',
    flexGrow: 1,
    flexBasis: 340,
    minWidth: 300,
  },
  tenantWidgetCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  moduleWidgetBlur: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  moduleWidgetCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  card: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 14,
    padding: 14,
    backgroundColor: 'transparent',
    overflow: 'hidden',
  },
  cardBlurWrap: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  cardTitle: {
    color: colors.white,
    fontSize: 15,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  cardBody: {
    marginTop: 8,
    gap: 8,
  },
  bodyText: {
    color: 'rgba(0,0,0,0.75)',
    fontSize: 13,
    lineHeight: 20,
  },
  bullet: {
    color: '#111111',
    fontSize: 14,
    lineHeight: 21,
  },
  diagram: {
    color: '#111111',
    fontFamily: 'monospace',
    fontSize: 12,
    lineHeight: 18,
  },
  pill: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.06)',
    borderRadius: 999,
    paddingHorizontal: 10,
    minHeight: 30,
    paddingVertical: 5,
    backgroundColor: 'rgba(0,0,0,0.04)',
    justifyContent: 'center',
  },
  pillActive: {
    borderColor: 'rgba(38,51,116,0.45)',
    backgroundColor: 'rgba(0,0,0,0.03)',
  },
  pillText: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '700',
  },
  pillTextActive: {
    color: colors.white,
  },
  inlineRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  builderHeaderRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: 12,
    flexWrap: 'wrap',
  },
  builderHeaderMeta: {
    flex: 1,
    minWidth: 240,
    gap: 4,
  },
  builderCreateModeBanner: {
    borderWidth: 1,
    borderColor: 'rgba(250,225,120,0.7)',
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.04)',
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginBottom: 8,
  },
  builderCreateModeBannerText: {
    color: '#FFF5C7',
    fontSize: 12,
    fontWeight: '800',
  },
  builderCreateModeBannerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  builderCreateModeBannerClose: {
    borderWidth: 1,
    borderColor: 'rgba(250,225,120,0.78)',
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.06)',
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  builderCreateModeBannerCloseText: {
    color: '#FFF5C7',
    fontSize: 11,
    fontWeight: '700',
  },
  builderStepRail: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
    marginTop: 2,
  },
  builderStepItem: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
    borderRadius: 999,
    backgroundColor: 'rgba(0,0,0,0.03)',
    paddingHorizontal: 10,
    minHeight: 30,
    paddingVertical: 6,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    justifyContent: 'center',
  },
  builderStepItemCurrent: {
    borderColor: 'rgba(250,225,120,0.9)',
    backgroundColor: 'rgba(0,0,0,0.92)',
    boxShadow: '0 0 10px rgba(253,224,120,0.5)',
    elevation: 6,
  },
  builderStepItemComplete: {
    borderColor: 'rgba(55,199,120,0.62)',
    backgroundColor: 'rgba(55,199,120,0.18)',
  },
  builderStepBullet: {
    width: 10,
    height: 10,
    borderRadius: 99,
  },
  builderStepBulletPending: {
    backgroundColor: '#8A8699',
  },
  builderStepBulletCurrent: {
    backgroundColor: '#FDE078',
    boxShadow: '0 0 8px rgba(253,224,120,0.7)',
    elevation: 8,
  },
  builderStepBulletComplete: {
    backgroundColor: '#37C778',
  },
  builderStepText: {
    color: '#1F2937',
    fontSize: 12,
    fontWeight: '700',
  },
  builderStepTextCurrent: {
    color: '#111111',
  },
  builderStepTextComplete: {
    color: '#DFFBEA',
  },
  builderLayout: {
    flexDirection: 'row',
    gap: 14,
    flexWrap: 'wrap',
    alignItems: 'flex-start',
  },
  builderSectionCard: {
    borderWidth: 1,
    borderColor: 'rgba(38,51,116,0.14)',
    borderRadius: 14,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(18px)',
    boxShadow: '0 4px 16px rgba(0,0,0,0.18)',
    overflow: 'hidden',
    paddingHorizontal: 14,
    paddingVertical: 12,
    gap: 8,
  },
  builderSectionTitle: {
    color: '#111111',
    fontSize: 14,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  builderSectionHint: {
    color: '#6B7280',
    fontSize: 11,
    lineHeight: 16,
  },
  builderStudioTextPrimary: {
    color: '#111111',
  },
  builderStudioTextSecondary: {
    color: '#6B7280',
  },
  builderActionRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    alignItems: 'center',
  },
  builderFormSection: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(38,51,116,0.14)',
    borderRadius: 14,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(18px)',
    boxShadow: '0 4px 16px rgba(0,0,0,0.18)',
    overflow: 'hidden',
    padding: 12,
  },
  builderFormSectionCompact: {
    flexDirection: 'column',
  },
  builderFormSectionHeader: {
    width: 192,
    gap: 4,
  },
  builderFormSectionHeaderRail: {
    alignSelf: 'stretch',
    borderRightWidth: 1,
    borderRightColor: 'rgba(0,0,0,0.03)',
    paddingRight: 14,
    marginRight: 4,
  },
  builderFormSectionHeaderCompact: {
    width: '100%',
    borderRightWidth: 0,
    paddingRight: 0,
    marginRight: 0,
    paddingBottom: 8,
  },
  builderFormSectionTitle: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: -0.2,
  },
  builderFormSectionText: {
    color: '#6B7280',
    fontSize: 11,
    lineHeight: 16,
  },
  builderFormSectionBody: {
    flex: 1,
    minWidth: 220,
    gap: 10,
  },
  builderConfigPane: {
    flex: 1,
    minWidth: 300,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 16,
    padding: 14,
    gap: 12,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
  },
  builderPreviewPane: {
    flex: 1,
    minWidth: 300,
  },
  builderPreviewCard: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 16,
    padding: 14,
    gap: 12,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
  },
  builderPreviewHeroCard: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 12,
    padding: 12,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    gap: 4,
  },
  builderPreviewHeroTitle: {
    color: '#111111',
    fontSize: 20,
    fontWeight: '800',
  },
  builderPreviewHeroSubtitle: {
    color: '#4B5563',
    fontSize: 13,
    fontWeight: '700',
  },
  builderPreviewStatsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  builderPreviewStatCard: {
    flex: 1,
    minWidth: 130,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 12,
    paddingHorizontal: 10,
    paddingVertical: 10,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    gap: 2,
  },
  builderPreviewStatValue: {
    color: '#111111',
    fontSize: 24,
    fontWeight: '800',
  },
  builderPreviewStatLabel: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '600',
  },
  builderPreviewFieldRow: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 12,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    padding: 10,
    gap: 6,
  },
  builderPreviewFieldMeta: {
    gap: 2,
  },
  builderDropZone: {
    borderWidth: 2,
    borderColor: 'rgba(0,0,0,0.12)',
    borderStyle: 'dashed',
    borderRadius: 14,
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  builderDetailsFormPanel: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 14,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    padding: 12,
    gap: 10,
  },
  builderDetailsFormPanelWide: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  builderDetailsFormRow: {
    gap: 7,
    width: '100%',
    paddingBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,211,50,0.18)',
  },
  builderDetailsFormRowHalf: {
    width: '48%',
  },
  builderDetailsFormLabel: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '700',
  },
  builderDetailsFormInput: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
    borderRadius: 10,
    backgroundColor: 'rgba(0,0,0,0.03)',
    minHeight: 38,
    paddingHorizontal: 10,
    paddingVertical: 8,
    justifyContent: 'center',
  },
  builderDetailsFormInputMulti: {
    minHeight: 72,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
  },
  builderDetailsFormInputText: {
    color: '#374151',
    fontSize: 12,
  },
  builderDetailsFormType: {
    color: '#6B7280',
    fontSize: 11,
  },
  endUserWorkspaceShell: {
    flexDirection: 'row',
    alignItems: 'stretch',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 12,
    overflow: 'hidden',
    backgroundImage: 'none',
    backgroundColor: '#111111',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
  },
  endUserWorkspaceShellCompact: {
    flexDirection: 'column',
  },
  endUserWorkspaceRail: {
    width: 300,
    borderRightWidth: 1,
    borderRightColor: 'rgba(0,0,0,0.03)',
    backgroundImage: 'none',
    backgroundColor: '#111111',
    backdropFilter: 'blur(14px)',
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 5,
  },
  endUserWorkspaceRailCompact: {
    width: '100%',
    borderRightWidth: 0,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.08)',
  },
  endUserWorkspaceRailLabel: {
    color: '#6B7280',
    fontSize: 11,
    fontWeight: '700',
    paddingHorizontal: 4,
  },
  endUserWorkspaceTab: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 9,
    minHeight: 54,
    justifyContent: 'center',
    gap: 2,
  },
  endUserWorkspaceTabActive: {
    borderWidth: 2,
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.04)',
  },
  endUserWorkspaceTabStep: {
    color: '#4B5563',
    fontSize: 12,
    fontWeight: '700',
    letterSpacing: 0.3,
  },
  endUserWorkspaceTabStepActive: {
    color: '#111111',
    fontWeight: '800',
  },
  endUserWorkspaceTabName: {
    color: '#6B7280',
    fontSize: 11,
  },
  endUserWorkspaceTabNameActive: {
    color: '#111111',
    fontWeight: '700',
  },
  endUserWorkspaceContent: {
    flex: 1,
    minWidth: 260,
    gap: 5,
    padding: 10,
  },
  endUserHierarchyGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  endUserHierarchyCard: {
    flexGrow: 1,
    minWidth: 170,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 12,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  endUserHierarchyCardText: {
    color: '#111111',
    fontSize: 12,
    fontWeight: '800',
  },
  inputWrap: {
    gap: 6,
  },
  inputLabelRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 8,
  },
  inputLabel: {
    color: 'rgba(0,0,0,0.88)',
    fontSize: 13,
  },
  inputHelperText: {
    color: 'rgba(232,236,255,0.58)',
    fontSize: 11,
    flexShrink: 1,
    textAlign: 'right',
  },
  input: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.03)',
    borderRadius: 14,
    backgroundColor: '#111111',
    color: colors.white,
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 13,
  },
  inputMulti: {
    minHeight: 84,
    textAlignVertical: 'top',
  },
  primaryButton: {
    borderRadius: 14,
    minHeight: 44,
    paddingHorizontal: 14,
    paddingVertical: 10,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.10)',
    backgroundImage: 'none',
    backgroundColor: '#111111',
    boxShadow: '0 8px 16px rgba(38,51,116,0.24), 0 18px 40px rgba(38,51,116,0.18)',
  },
  primaryButtonText: {
    color: '#fff',
    fontWeight: '800',
    fontSize: 13,
  },
  buttonDisabled: {
    opacity: 0.45,
  },
  secondaryButton: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    minHeight: 36,
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#111111',
    justifyContent: 'center',
  },
  secondaryButtonText: {
    color: 'rgba(232,236,255,0.9)',
    fontSize: 12,
    fontWeight: '700',
  },
  /* ── Shared / Orbital shared keys ─────────────────────── */
  sectionTitle: {
    color: '#F1F5F9',
    fontSize: 18,
    fontWeight: '800',
    marginBottom: 4,
  },
  sectionDetail: {
    color: 'rgba(0,0,0,0.6)',
    fontSize: 13,
    lineHeight: 19,
  },
  sectionBody: {
    flex: 1,
  },
  adminSidebar: {
    backgroundColor: 'rgba(0,0,0,0.03)',
    paddingTop: 8,
  },
  textInput: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 8,
    color: '#F1F5F9',
    fontSize: 14,
    backgroundColor: '#111111',
  },
  pillButton: {
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    backgroundColor: '#111111',
  },
  pillButtonActive: {
    borderColor: '#111111',
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  pillButtonText: {
    color: '#374151',
    fontSize: 12,
    fontWeight: '600',
  },
  pillButtonTextActive: {
    color: '#B0C4E8',
    fontWeight: '700',
  },
  listCard: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 4px 16px rgba(0,0,0,0.18)',
    overflow: 'hidden',
    padding: 14,
    gap: 4,
  },
  listTitle: {
    color: 'rgba(232,236,255,0.96)',
    fontSize: 14,
    fontWeight: '800',
  },
  stageChip: {
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    alignSelf: 'flex-start',
  },
  stageChipText: {
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 0.5,
  },
  stageReceived: { backgroundColor: 'rgba(59,130,246,0.22)' },
  stageReceivedText: { color: '#93C5FD' },
  stageTriage: { backgroundColor: 'rgba(249,115,22,0.22)' },
  stageTriageText: { color: '#FDBA74' },
  stageRepair: { backgroundColor: 'rgba(168,85,247,0.22)' },
  stageRepairText: { color: '#6B7280' },
  stageQC: { backgroundColor: 'rgba(234,179,8,0.22)' },
  stageQCText: { color: '#FDE68A' },
  stageShipped: { backgroundColor: 'rgba(34,197,94,0.22)' },
  stageShippedText: { color: '#86EFAC' },
  stageRisk: { backgroundColor: 'rgba(239,68,68,0.22)' },
  stageRiskText: { color: '#FCA5A5' },
  stageActive: { backgroundColor: 'rgba(34,197,94,0.18)' },
  stageActiveText: { color: '#86EFAC' },
  kpiRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  kpiCard: {
    flex: 1,
    minWidth: 120,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    padding: 10,
    gap: 2,
    alignItems: 'center',
  },
  kpiValue: {
    color: '#111111',
    fontSize: 22,
    fontWeight: '800',
  },
  kpiLabel: {
    color: 'rgba(232,236,255,0.6)',
    fontSize: 10,
    fontWeight: '600',
    textAlign: 'center',
  },
  kpiSub: {
    color: 'rgba(232,236,255,0.4)',
    fontSize: 9,
    textAlign: 'center',
  },
  dataHeaderRow: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.03)',
    paddingBottom: 4,
    marginBottom: 4,
    gap: 4,
  },
  dataHeaderCell: {
    flex: 1,
    minWidth: 60,
  },
  dataHeaderText: {
    color: 'rgba(0,0,0,0.45)',
    fontSize: 9,
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
  },
  dataRow: {
    flexDirection: 'row',
    gap: 4,
    paddingVertical: 4,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255,255,255,0.04)',
  },
  dataCell: {
    flex: 1,
    minWidth: 60,
  },
  dataCellText: {
    color: 'rgba(232,236,255,0.82)',
    fontSize: 11,
  },
  dataCellBold: {
    color: 'rgba(232,236,255,0.96)',
    fontSize: 11,
    fontWeight: '700',
  },
  dataCellMoney: {
    color: '#86EFAC',
    fontSize: 11,
    fontWeight: '700',
  },
  searchToolbar: {
    flexDirection: 'row',
    gap: 8,
    alignItems: 'center',
    marginBottom: 6,
  },
  searchInput: {
    flex: 1,
    minHeight: 34,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.03)',
    backgroundColor: '#111111',
    paddingHorizontal: 10,
    color: 'rgba(232,236,255,0.9)',
    fontSize: 12,
  },
  detailPanel: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    padding: 10,
    gap: 6,
  },
  detailFieldGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  detailField: {
    minWidth: 100,
    gap: 1,
  },
  detailFieldLabel: {
    color: 'rgba(232,236,255,0.44)',
    fontSize: 9,
    fontWeight: '700',
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  detailFieldValue: {
    color: 'rgba(232,236,255,0.92)',
    fontSize: 12,
  },
  tagBadge: {
    paddingHorizontal: 6,
    paddingVertical: 1,
    borderRadius: 4,
    backgroundColor: 'rgba(0,0,0,0.06)',
    alignSelf: 'flex-start',
  },
  tagBadgeText: {
    color: '#6B7280',
    fontSize: 9,
    fontWeight: '700',
  },
  metaText: {
    color: 'rgba(232,236,255,0.66)',
    fontSize: 10,
    lineHeight: 14,
  },
  separator: {
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.03)',
    marginVertical: 4,
  },
  notice: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '700',
  },
  loadingWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: colors.midnight900,
    gap: 10,
  },
  loadingText: {
    color: '#1F2937',
    fontSize: 13,
  },
  emptyWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyText: {
    color: '#4B5563',
  },
  processCard: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    borderRadius: 12,
    padding: 14,
    gap: 10,
  },
  processTitle: {
    color: colors.white,
    fontSize: 14,
    fontWeight: '800',
  },
  stepRow: {
    flexDirection: 'row',
    gap: 8,
  },
  stepItem: {
    flex: 1,
    gap: 6,
    alignItems: 'center',
  },
  stepDot: {
    width: 26,
    height: 26,
    borderRadius: 99,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.12)',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.06)',
  },
  stepDotActive: {
    borderColor: 'rgba(0,0,0,0.12)',
    backgroundColor: 'rgba(0,0,0,0.08)',
  },
  stepDotText: {
    color: '#111111',
    fontSize: 12,
    fontWeight: '700',
  },
  stepDotTextActive: {
    color: '#111111',
  },
  stepLabel: {
    color: '#4B5563',
    fontSize: 11,
    fontWeight: '600',
    textAlign: 'center',
  },
  stepLabelActive: {
    color: colors.white,
  },
  hintRow: {
    gap: 8,
  },
  hintBubble: {
    width: 240,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: 'rgba(0,0,0,0.03)',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    padding: 12,
    gap: 6,
  },
  hintBubbleTitle: {
    color: colors.white,
    fontSize: 13,
    fontWeight: '800',
  },
  hintBubbleText: {
    color: '#1F2937',
    fontSize: 11,
    lineHeight: 16,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0,0,0,0.4)',
    padding: 20,
  },
  modalCard: {
    width: '100%',
    maxWidth: 420,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: 'rgba(255,255,255,0.98)',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
    overflow: 'hidden',
    padding: 16,
    gap: 10,
  },
  modalTitle: {
    color: colors.white,
    fontSize: 17,
    fontWeight: '800',
  },
  modalText: {
    color: '#1F2937',
    fontSize: 14,
    lineHeight: 21,
  },
  authWrap: {
    flex: 1,
    backgroundColor: '#111111',
    backgroundImage: 'none',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 18,
  },
  authCard: {
    width: '100%',
    maxWidth: 440,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: 'rgba(0,0,0,0.92)',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
    overflow: 'hidden',
    padding: 24,
    gap: 14,
  },
  authTitle: {
    color: colors.white,
    fontSize: 24,
    fontWeight: '800',
  },
  authSubTitle: {
    color: 'rgba(0,0,0,0.6)',
    fontSize: 14,
    lineHeight: 20,
  },
  authDividerWrap: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  authDividerLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(0,0,0,0.03)',
  },
  authDividerText: {
    color: 'rgba(232,236,255,0.55)',
    fontSize: 11,
    fontWeight: '700',
    letterSpacing: 0.25,
  },
  socialButton: {
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    paddingHorizontal: 14,
    minHeight: 44,
    paddingVertical: 10,
    backgroundColor: '#111111',
    backdropFilter: 'blur(14px)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  socialButtonText: {
    color: 'rgba(232,236,255,0.86)',
    fontWeight: '700',
    fontSize: 14,
    textAlign: 'center',
  },
  linkText: {
    color: colors.gold100,
    fontSize: 12,
    fontWeight: '700',
    textAlign: 'center',
  },
  landingWrap: {
    flex: 1,
    backgroundColor: 'transparent',
  },
  landingContent: {
    flexGrow: 1,
    paddingBottom: 36,
  },
  landingTopBar: {
    width: '100%',
    maxWidth: 560,
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 999,
    paddingHorizontal: 18,
    paddingVertical: 10,
    marginTop: 12,
    marginBottom: 20,
    backgroundImage: 'linear-gradient(180deg, rgba(0,0,0,0.03), rgba(0,0,0,0.01))',
    backgroundColor: 'rgba(0,0,0,0.02)',
    backdropFilter: 'blur(18px)',
    boxShadow: '0 12px 40px rgba(0,0,0,0.35)',
  },
  landingTopBrand: {
    color: '#111111',
    fontSize: 15,
    fontWeight: '800',
  },
  landingTopMenu: {
    flexDirection: 'row',
    gap: 8,
  },
  landingTopMenuButton: {
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundColor: '#111111',
    borderRadius: 999,
    paddingHorizontal: 12,
    minHeight: 34,
    paddingVertical: 6,
    justifyContent: 'center',
  },
  landingTopMenuButtonActive: {
    borderColor: 'rgba(38,51,116,0.55)',
    backgroundColor: 'rgba(0,0,0,0.03)',
  },
  landingTopMenuText: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '700',
  },
  landingTopMenuTextActive: {
    color: '#111111',
  },
  landingHeroSection: {
    minHeight: 640,
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 36,
    gap: 16,
  },
  landingHeroIconWrap: {
    width: 56,
    height: 56,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'linear-gradient(180deg, rgba(0,0,0,0.03), rgba(0,0,0,0.01))',
    backgroundColor: 'rgba(0,0,0,0.03)',
    backdropFilter: 'blur(14px)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  landingHeroIcon: {
    color: '#111111',
    fontSize: 22,
    fontWeight: '700',
  },
  landingHeroTitle: {
    color: '#111111',
    fontSize: 62,
    lineHeight: 66,
    fontWeight: '800',
    textAlign: 'center',
    maxWidth: 980,
  },
  landingHeroSubtitle: {
    color: '#4B5563',
    fontSize: 21,
    lineHeight: 31,
    textAlign: 'center',
    maxWidth: 920,
  },
  landingHeroActions: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 6,
  },
  landingPrimaryCta: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.10)',
    backgroundImage: 'none',
    backgroundColor: '#111111',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
    minHeight: 44,
    paddingHorizontal: 18,
    paddingVertical: 11,
    justifyContent: 'center',
  },
  landingPrimaryCtaText: {
    color: '#111111',
    fontSize: 14,
    fontWeight: '700',
  },
  landingSecondaryCta: {
    borderRadius: 999,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundColor: '#111111',
    backdropFilter: 'blur(14px)',
    minHeight: 44,
    paddingHorizontal: 18,
    paddingVertical: 11,
    justifyContent: 'center',
  },
  landingSecondaryCtaText: {
    color: '#111111',
    fontSize: 14,
    fontWeight: '700',
  },
  landingTrustText: {
    marginTop: 20,
    color: '#6B7280',
    fontSize: 13,
    fontWeight: '600',
  },
  landingLogosRow: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'center',
    flexWrap: 'wrap',
    gap: 18,
    marginTop: 2,
  },
  landingLogoItem: {
    color: '#374151',
    fontSize: 16,
    fontWeight: '600',
  },
  landingShowcaseSection: {
    width: '100%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: '#FAFAFA',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
    paddingHorizontal: 20,
    paddingVertical: 22,
    gap: 14,
  },
  landingSectionTitle: {
    color: '#111111',
    fontSize: 34,
    lineHeight: 40,
    fontWeight: '800',
  },
  landingSectionEyebrow: {
    color: '#111111',
    fontSize: 11,
    fontWeight: '800',
    letterSpacing: 1,
  },
  landingSectionText: {
    color: '#4B5563',
    fontSize: 17,
    lineHeight: 26,
  },
  landingFeatureGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
    marginTop: 4,
  },
  landingFeatureCard: {
    flex: 1,
    minWidth: 210,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: '#111111',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
    overflow: 'hidden',
    borderRadius: 12,
    padding: 14,
    gap: 6,
  },
  landingFeatureTitle: {
    color: '#111111',
    fontSize: 15,
    fontWeight: '700',
  },
  landingFeatureText: {
    color: '#4B5563',
    fontSize: 12,
    lineHeight: 18,
  },
  landingShowcasePanel: {
    marginTop: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backgroundImage: 'none',
    backgroundColor: '#111111',
    backdropFilter: 'blur(14px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.03)',
    overflow: 'hidden',
  },
  landingShowcaseHeader: {
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(0,0,0,0.06)',
    backgroundColor: '#FAFAFA',
  },
  landingShowcaseHeaderText: {
    color: '#1F2937',
    fontSize: 12,
    fontWeight: '600',
  },
  landingShowcaseGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    padding: 12,
    gap: 10,
  },
  landingShowcaseColumn: {
    flex: 1,
    minWidth: 220,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 12,
    backgroundImage: 'none',
    backgroundColor: 'transparent',
    backdropFilter: 'blur(14px)',
    boxShadow: 'none',
    overflow: 'hidden',
    padding: 10,
    gap: 6,
  },
  landingShowcaseColumnTitle: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '800',
  },
  landingShowcaseItem: {
    color: '#4B5563',
    fontSize: 12,
    lineHeight: 17,
  },
  landingBottomActions: {
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
  },
  adminShell: {
    flexDirection: 'row',
    gap: 0,
    alignItems: 'flex-start',
    flex: 1,
  },
  adminNavPane: {
    width: 264,
    minWidth: 264,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 16,
    backgroundImage: 'none',
    backgroundColor: '#111111',
    backdropFilter: 'blur(20px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04)',
    overflow: 'hidden',
    paddingVertical: 12,
    paddingHorizontal: 8,
    gap: 2,
    alignSelf: 'stretch',
  },
  adminNavPaneCompact: {
    width: '100%',
    minWidth: 0,
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignSelf: 'auto',
    borderRadius: 16,
    paddingHorizontal: 10,
    paddingVertical: 10,
    gap: 6,
  },
  adminNavSection: {
    gap: 2,
  },
  adminNavSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 14,
    paddingVertical: 11,
    borderRadius: 12,
    backgroundColor: 'transparent',
    gap: 8,
  },
  adminNavSectionHeaderActive: {
    backgroundColor: 'rgba(0,0,0,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  adminNavSectionHeaderLabel: {
    color: '#111111',
    fontSize: 13,
    fontWeight: '800',
    letterSpacing: -0.2,
    flex: 1,
  },
  adminNavSectionChevron: {
    color: '#111111',
    fontSize: 11,
    fontWeight: '700',
  },
  adminNavSectionDescription: {
    color: 'rgba(232,236,255,0.55)',
    fontSize: 10,
    lineHeight: 14,
    paddingHorizontal: 14,
    paddingBottom: 6,
    paddingTop: 2,
  },
  adminNavItem: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    paddingLeft: 26,
    borderRadius: 10,
    backgroundColor: 'transparent',
  },
  adminNavItemActive: {
    backgroundColor: 'rgba(0,0,0,0.03)',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
  },
  adminNavItemLabel: {
    color: '#6B7280',
    fontSize: 12,
    fontWeight: '600',
  },
  adminNavItemLabelActive: {
    color: '#111111',
    fontWeight: '700',
  },
  adminNavItemDetail: {
    color: 'rgba(0,0,0,0.4)',
    fontSize: 10,
    lineHeight: 13,
    paddingTop: 2,
  },
  adminContentPane: {
    flex: 1,
    minWidth: 320,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    borderRadius: 16,
    backgroundImage: 'none',
    backgroundColor: '#111111',
    backdropFilter: 'blur(20px)',
    boxShadow: '0 1px 3px rgba(0,0,0,0.06), 0 4px 16px rgba(0,0,0,0.04)',
    overflow: 'hidden',
    paddingLeft: 16,
    paddingRight: 16,
    paddingVertical: 12,
    gap: 14,
    marginLeft: 12,
  },
  adminContentPaneCompact: {
    paddingLeft: 12,
    paddingTop: 12,
    marginLeft: 0,
    marginTop: 8,
  },
  adminContentHeader: {
    backgroundImage: 'none',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.08)',
    backdropFilter: 'blur(18px)',
    padding: 20,
    gap: 8,
  },
  adminContentTitle: {
    color: '#111111',
    fontSize: 20,
    fontWeight: '800',
    letterSpacing: -0.3,
  },
  adminContentDescription: {
    color: 'rgba(0,0,0,0.6)',
    fontSize: 13,
    lineHeight: 20,
  },
};

// Both day and night modes now share the same white/black modern theme.

const styles = StyleSheet.create(nightStyleObject as any);

export function getStyles(_mode: ThemeMode) {
  return styles;
}
